mysql:
 hostname: localhost
 port: 3306
 socket: /tmp/mysql.sock
 username: root
 password: 
 database: ws_cafe_development

destination:
 postgres:
  hostname: localhost
  port: 5432
  username: postgres
  password: postgres
  database: ws_cafe_development